services:

  postgres:
    image: postgres:16
    container_name: habit_postgres_prod
    restart: unless-stopped
    env_file:
      - ../backend/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "habit_admin", "-d", "habit_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: habit_backend_prod
    restart: unless-stopped
    env_file:
      - ../backend/.env.prod
    depends_on:
      - postgres
    expose:
      - "3000"
    networks:
      - habit-net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: habit_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - habit-net


networks:
  habit-net:

volumes:
  postgres_data: